/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer.view;
import Customer.controller.CustomerController;
import Customer.model.CustomerModel;


import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Uthsara Basnayake
 */
public class CustomerView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    private final CustomerController customercontroller;
    public CustomerView() {
        customercontroller= new CustomerController();
      
        initComponents();
        loadAllCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        basePanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        custId = new javax.swing.JLabel();
        custIdText = new javax.swing.JTextField();
        custName = new javax.swing.JLabel();
        custFirstNameText = new javax.swing.JTextField();
        custAddress = new javax.swing.JLabel();
        custAddressText = new javax.swing.JTextField();
        custAge = new javax.swing.JLabel();
        custAgeText = new javax.swing.JTextField();
        custZip = new javax.swing.JLabel();
        custLastNameText = new javax.swing.JTextField();
        custName1 = new javax.swing.JLabel();
        custTitle = new javax.swing.JLabel();
        custTitlebox = new javax.swing.JComboBox<>();
        custziptext = new javax.swing.JTextField();
        custGender = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        mobile = new javax.swing.JLabel();
        mobileText = new javax.swing.JTextField();
        genderText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        headerLabel.setText("Manage Customer");

        custId.setText("ID");

        custName.setText("First Name");

        custFirstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custFirstNameTextActionPerformed(evt);
            }
        });

        custAddress.setText("Address");

        custAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custAddressTextActionPerformed(evt);
            }
        });

        custAge.setText("Age");

        custAgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custAgeTextActionPerformed(evt);
            }
        });

        custZip.setText("Zip Code");

        custLastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custLastNameTextActionPerformed(evt);
            }
        });

        custName1.setText("Last Name");

        custTitle.setText("Title");

        custTitlebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Miss", "Mrs.", "Rev." }));
        custTitlebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custTitleboxActionPerformed(evt);
            }
        });

        custGender.setText("Gender");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        mobile.setText("Mobile");

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(custId)
                    .addComponent(custName)
                    .addComponent(custAddress)
                    .addComponent(custAge)
                    .addComponent(custZip)
                    .addComponent(custTitle)
                    .addComponent(custGender))
                .addGap(58, 58, 58)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                        .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(basePanelLayout.createSequentialGroup()
                                .addComponent(custAgeText)
                                .addGap(101, 101, 101)
                                .addComponent(mobile)
                                .addGap(63, 63, 63)
                                .addComponent(mobileText))
                            .addComponent(custAddressText)
                            .addGroup(basePanelLayout.createSequentialGroup()
                                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(custIdText, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(custFirstNameText))
                                .addGap(97, 97, 97)
                                .addComponent(custName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(custLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custTitlebox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custziptext, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                        .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addGap(32, 32, 32)
                        .addComponent(saveButton)
                        .addGap(35, 35, 35)
                        .addComponent(deleteButton)
                        .addGap(102, 102, 102))))
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custId)
                    .addComponent(custIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custTitle)
                    .addComponent(custTitlebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(custName)
                    .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(custFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(custName1)
                        .addComponent(custLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addComponent(custAddress)
                        .addGap(24, 24, 24)
                        .addComponent(custZip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(custAge))
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addComponent(custAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(custziptext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile)
                            .addComponent(mobileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custGender)
                    .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(saveButton)
                    .addComponent(deleteButton))
                .addGap(41, 41, 41)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custAddressTextActionPerformed

    private void custFirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custFirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custFirstNameTextActionPerformed

    private void custLastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custLastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custLastNameTextActionPerformed

    private void custTitleboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custTitleboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custTitleboxActionPerformed

    private void custAgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custAgeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custAgeTextActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
               saveCustomer();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
       deleteCustomer();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updateCustomer();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        searchCustomer();
    }//GEN-LAST:event_customerTableMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel custAddress;
    private javax.swing.JTextField custAddressText;
    private javax.swing.JLabel custAge;
    private javax.swing.JTextField custAgeText;
    private javax.swing.JTextField custFirstNameText;
    private javax.swing.JLabel custGender;
    private javax.swing.JLabel custId;
    private javax.swing.JTextField custIdText;
    private javax.swing.JTextField custLastNameText;
    private javax.swing.JLabel custName;
    private javax.swing.JLabel custName1;
    private javax.swing.JLabel custTitle;
    private javax.swing.JComboBox<String> custTitlebox;
    private javax.swing.JLabel custZip;
    private javax.swing.JTable customerTable;
    private javax.swing.JTextField custziptext;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField genderText;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mobile;
    private javax.swing.JTextField mobileText;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

 private void saveCustomer(){
        CustomerModel cm;
        cm = new CustomerModel(custIdText.getText(),(String)custTitlebox.getSelectedItem(),custFirstNameText.getText(), custLastNameText.getText(),custAddressText.getText(),custziptext.getText(),(int)Double.parseDouble(custAgeText.getText()),mobileText.getText(),genderText.getText());
        try {
            String resp=customercontroller.saveCustomer(cm);
            JOptionPane.showMessageDialog(this,resp);
            
            loadAllCustomers();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }
private void deleteCustomer() {
        CustomerModel cm = new CustomerModel(custIdText.getText(),(String)custTitlebox.getSelectedItem(),custFirstNameText.getText(), custLastNameText.getText(),custAddressText.getText(),custziptext.getText(),(int)Double.parseDouble(custAge.getText()),mobileText.getText(),genderText.getText());
        try {
            String resp=customercontroller.deleteCustomer(cm);
            JOptionPane.showMessageDialog(this,resp);
             clear();
            loadAllCustomers();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
}
    
        private void updateCustomer() {
        CustomerModel cm = new CustomerModel(custIdText.getText(),(String)custTitlebox.getSelectedItem(),custFirstNameText.getText(), custLastNameText.getText(),custAddressText.getText(),custziptext.getText(),(int)Double.parseDouble(custAge.getText()),mobileText.getText(),genderText.getText());
        try {
            String resp=customercontroller.updateCustomer(cm);
            JOptionPane.showMessageDialog(this,resp);
            clear();
            loadAllCustomers();
        } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }
 private void clear() {
       custIdText.setText("");
     custFirstNameText.setText("");
        custLastNameText.setText("");
        custAddressText.setText("");
        custziptext.setText("");
        custAge.setText("");
        mobileText.setText("");
        genderText.setText("");
        
        
 }
 private void loadAllCustomers(){
    
        try{
        String [] collumns ={"ID","Title","FirstName","LastName","Address","Zip","Age","Mobile","Gender"};
    DefaultTableModel dtm = new DefaultTableModel(collumns,0){
  @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            customerTable.setModel(dtm);
      
            ArrayList<CustomerModel> cm = CustomerController.getAllCustomers();

            for (CustomerModel customer : cm) {
                Object[] rowData = {customer.getId(),customer.getTitle(), customer.getFirstName() , customer.getLastName(),customer.getAddress(),customer.getZipcode(),customer.getAge(),customer.getMobile(),customer.getGender()};
                dtm.addRow(rowData);
            }
        }catch (SQLException ex) {
           Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        
}  
 }
 
 private void searchCustomer(){
        try {
            String id=customerTable.getValueAt(customerTable.getSelectedRow(), 0).toString();
            CustomerModel customermodel=customercontroller.searchCustomer(id);
            if(customermodel!=null){
                custIdText.setText(customermodel.getId());
                custTitlebox.setToolTipText(customermodel.getTitle());
                custFirstNameText.setText(customermodel.getFirstName());
                custLastNameText.setText(customermodel.getLastName());
                custAddressText.setText(customermodel.getAddress());
                custziptext.setText(customermodel.getZipcode());
                custAge.setText(Integer.toString(customermodel.getAge()));
                mobileText.setText(customermodel.getMobile());
                genderText.setText(customermodel.getGender());
            }else{
                JOptionPane.showMessageDialog(this, "Customer Not Found");
                
            }  } catch (SQLException ex) {
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
        }
 }
}

 

